# Site settings
title: "Jeffrey C Reed Resume"
description: "A resume for Jeffrey C Reed."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jeffrey C. Reed"
resume_title:                   "Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jcreed063@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "716-445-0254"
resume_contact_address:         "147 Willowridge Drive, Amherst NY 14228"

resume_header_contact_info:     "147 Willowridge Drive, Amherst • 716-445-0254 • jcreed063@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm an experienced Software Engineer skilled in Ruby on Rails, JavaScript and PostgreSQL. A technical team lead for 6 Engineers on a large scale Rails project who is passionate about clean code and test driven development.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jcreed"
  resume_twitter_url:           "http://twitter.com/jcreed63"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jeff-c-reed"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           ""
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
